version: '3'
services:
  app:
    container_name: ManagementData
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:jdbc:postgresql://host.docker.internal:5434/EnergyManagementSystem-Device
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mmma